motors:
  motor1:
    gear_ratio: 140.0
    step_resolution: 800
    joints:
      - index: 0
        ratio: -1.0
  motor2:
    gear_ratio: 56.0
    step_resolution: 800
    joints:
      - index: 1
        ratio: 1.0
  motor3:
    gear_ratio: 56.0
    step_resolution: 800
    joints:
      - index: 2
        ratio: 1.0
  motor4:
    gear_ratio: 125.78125
    step_resolution: 800
    joints:
      - index: 3
        ratio: -1.0
  motor5:
    gear_ratio: 19.047619047619047
    step_resolution: 800
    joints:
      - index: 4
        ratio: -0.5
      - index: 5
        ratio: -0.5
  motor6:
    gear_ratio: 19.047619047619047
    step_resolution: 800
    joints:
      - index: 4
        ratio: -0.5
      - index: 5
        ratio: 0.5
